app:
  path:     /
  defaults: { _controller: AppBundle:Default:index }

completedList:
  path:     /completed
  defaults: { _controller: AppBundle:Default:completedList }
  methods: [ GET ]

activeList:
  path:     /active
  defaults: { _controller: AppBundle:Default:activeList }
  methods: [ GET ]

closeItem:
  path: /close/{id}
  defaults: { _controller: AppBundle:Default:close }
  methods: [ GET ]
