<?php

namespace AppBundle\Entity\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllActive()
    {
        return $this->findBy(['status' => 'open']);
    }

    public function findAllCompleted()
    {
        return $this->findBy(['status' => 'close']);
    }
}
